#!/usr/bin/env bash

################################################################################
# Pretend to be xwininfo.
set -eu
set -o pipefail

################################################################################
function _su() {
  if [ "$(whoami)" != "pjones" ]; then
    su - pjones -c "$*"
  else
    "$@"
  fi
}

################################################################################
function get_windows() {
  _su swaymsg -t get_tree |
    jq --raw-output \
      '[recurse(.nodes[], .floating_nodes[])]
     | map(select((.type == "con" or .type == "floating_con") and .name))
     | map(.name)
     | join("\u0000")'
}

################################################################################
function main() {
  while IFS= read -r -d '' window; do
    echo "0x00 \"$window\""
  done < <(get_windows | tr --delete '"' | tr "\n" "\0")
}

################################################################################
main "$@"
