#!/usr/bin/env bash

################################################################################
# Pretend to be xwininfo.
set -eu
set -o pipefail

################################################################################
function _su() {
  if [ "$(whoami)" != "pjones" ]; then
    su - pjones -c "$*"
  else
    "$@"
  fi
}

################################################################################
function get_windows() {
  _su niri msg --json windows |
    jq --raw-output 'map(.title) | join("\u0000")'
}

################################################################################
function main() {
  while IFS= read -r -d '' window; do
    echo "0x00 \"$window\""
  done < <(get_windows | tr --delete '"' | tr "\n" "\0")
}

################################################################################
main "$@"
